ALTER TABLE HEART MODIFY HEART_MEM_NO NOT NULL;


ALTER TABLE HEART RENAME CONSTRAINT SYS_C008968 TO H_HEART_MEM_NO_NN;
------------------------------------------------
-- MYPAGE_P_COLLECTION 페이지가 있으신 분이 돌릴 쿼리
------------------------------------------------
ALTER TABLE MYPAGE_P_COLLECTION ADD CLT_WRITER_ID VARCHAR2(200);
COMMENT ON COLUMN MYPAGE_P_COLLECTION.CLT_WRITER_ID IS '컬렉션작성자아이디';

-- 컬럼 만들면 NULL 이 있는데, 제약조건 NOT NULL 을 걸어야되기 때문에 위배되기 때문
UPDATE MYPAGE_P_COLLECTION SET CLT_WRITER_ID='admin';
ALTER TABLE MYPAGE_P_COLLECTION MODIFY CLT_WRITER_ID NOT NULL;

-- ★★ 여기까지 돌리고 () 부분에 NN 제약조건 이름 넣기
ALTER TABLE MYPAGE_P_COLLECTION RENAME CONSTRAINT SYS_C008971 TO MPC_WRITER_NO_NN;




-- 잘못만든 컬럼 삭제
--ALTER TABLE MYPAGE_P_COLLECTION DROP COLUMN CLT_WRITER_NO;


DROP TABLE TEST;
CREATE TABLE TEST(
CLT_WRITER_ID VARCHAR2(200) CONSTRAINT MPC_WRITER_ID_NN NOT NULL
)

-- writerId 우겨넣는 쿼리
--UPDATE MYPAGE_P_COLLECTION
--SET CLT_WRITER_ID = 'sdaaeeng'
--WHERE MEMBER_NO=21;

commit;


SELECT * 
FROM MYPAGE_P_COLLECTION
WHERE CLT_STATUS = 'Y'
    AND CLT_WRITER_ID = 'sdaaeng'
ORDER BY CLT_NO DESC
