-- 더미유저 (99명)
-- 2/20 남 10대 1
INSERT INTO MEMBER VALUES(SEQ_MEM_MEMBER_NO.NEXTVAL, '개인', 'member04', '1111', 'member02@collaverse.co.kr', '01022222222', '개인회원04', 'profile_basic.png', NULL, NULL, DEFAULT, DEFAULT, DEFAULT, '10', 'man');

-- 3/11 남 20대 17
BEGIN
    FOR N IN 1..17
    LOOP
        INSERT INTO MEMBER VALUES(SEQ_MEM_MEMBER_NO.NEXTVAL, '개인', 'member' || SEQ_MEM_MEMBER_NO.CURRVAL, '1111', 'member02@collaverse.co.kr', '01022222222', '개인회원'|| SEQ_MEM_MEMBER_NO.CURRVAL, 'profile_basic.png', NULL, NULL, DEFAULT, DEFAULT, DEFAULT, '20', 'man');
    END LOOP;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/

COMMIT;

-- 3/12 남 20대 8
BEGIN
    FOR N IN 1..8
    LOOP
        INSERT INTO MEMBER VALUES(SEQ_MEM_MEMBER_NO.NEXTVAL, '개인', 'member'|| SEQ_MEM_MEMBER_NO.CURRVAL, '1111', 'member02@collaverse.co.kr', '01022222222', '개인회원'|| SEQ_MEM_MEMBER_NO.CURRVAL, 'profile_basic.png', NULL, NULL, DEFAULT, DEFAULT, DEFAULT, '20', 'man');
    END LOOP;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/

COMMIT;

-- 3/13 남 50대 7
BEGIN
    FOR N IN 1..7
    LOOP
        INSERT INTO MEMBER VALUES(SEQ_MEM_MEMBER_NO.NEXTVAL, '개인', 'member'|| SEQ_MEM_MEMBER_NO.CURRVAL, '1111', 'member02@collaverse.co.kr', '01022222222', '개인회원'|| SEQ_MEM_MEMBER_NO.CURRVAL, 'profile_basic.png', NULL, NULL, DEFAULT, DEFAULT, DEFAULT, '50', 'man');
    END LOOP;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/

COMMIT;

-- 3/13 여 30대 3
BEGIN
    FOR N IN 1..3
    LOOP
        INSERT INTO MEMBER VALUES(SEQ_MEM_MEMBER_NO.NEXTVAL, '개인', 'member'|| SEQ_MEM_MEMBER_NO.CURRVAL, '1111', 'member02@collaverse.co.kr', '01022222222', '개인회원'|| SEQ_MEM_MEMBER_NO.CURRVAL, 'profile_basic.png', NULL, NULL, DEFAULT, DEFAULT, DEFAULT, '30', 'woman');
    END LOOP;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/

COMMIT;

-- 3/14 여 30대 10
BEGIN
    FOR N IN 1..10
    LOOP
        INSERT INTO MEMBER VALUES(SEQ_MEM_MEMBER_NO.NEXTVAL, '개인', 'member'|| SEQ_MEM_MEMBER_NO.CURRVAL, '1111', 'member02@collaverse.co.kr', '01022222222', '개인회원'|| SEQ_MEM_MEMBER_NO.CURRVAL, 'profile_basic.png', NULL, NULL, DEFAULT, DEFAULT, DEFAULT, '30', 'woman');
    END LOOP;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/

COMMIT;

-- 3/15 여 30대 15
BEGIN
    FOR N IN 1..15
    LOOP
        INSERT INTO MEMBER VALUES(SEQ_MEM_MEMBER_NO.NEXTVAL, '개인', 'member'|| SEQ_MEM_MEMBER_NO.CURRVAL, '1111', 'member02@collaverse.co.kr', '01022222222', '개인회원'|| SEQ_MEM_MEMBER_NO.CURRVAL, 'profile_basic.png', NULL, NULL, DEFAULT, DEFAULT, DEFAULT, '30', 'woman');
    END LOOP;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/

COMMIT;

-- 3/16 여 40대 8
BEGIN
    FOR N IN 1..8
    LOOP
        INSERT INTO MEMBER VALUES(SEQ_MEM_MEMBER_NO.NEXTVAL, '개인', 'member'|| SEQ_MEM_MEMBER_NO.CURRVAL, '1111', 'member02@collaverse.co.kr', '01022222222', '개인회원'|| SEQ_MEM_MEMBER_NO.CURRVAL, 'profile_basic.png', NULL, NULL, DEFAULT, DEFAULT, DEFAULT, '40', 'woman');
    END LOOP;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/

COMMIT;

-- 3/17 여 30대 5
BEGIN
    FOR N IN 1..5
    LOOP
        INSERT INTO MEMBER VALUES(SEQ_MEM_MEMBER_NO.NEXTVAL, '개인', 'member'|| SEQ_MEM_MEMBER_NO.CURRVAL, '1111', 'member02@collaverse.co.kr', '01022222222', '개인회원'|| SEQ_MEM_MEMBER_NO.CURRVAL, 'profile_basic.png', NULL, NULL, DEFAULT, DEFAULT, DEFAULT, '30', 'woman');
    END LOOP;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/

COMMIT;

-- 3/17 여 10대 10
BEGIN
    FOR N IN 1..10
    LOOP
        INSERT INTO MEMBER VALUES(SEQ_MEM_MEMBER_NO.NEXTVAL, '개인', 'member'|| SEQ_MEM_MEMBER_NO.CURRVAL, '1111', 'member02@collaverse.co.kr', '01022222222', '개인회원'|| SEQ_MEM_MEMBER_NO.CURRVAL, 'profile_basic.png', NULL, NULL, DEFAULT, DEFAULT, DEFAULT, '10', 'woman');
    END LOOP;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/

COMMIT;

-- 3/18 X

-- 3/19 여 40대 10명
BEGIN
    FOR N IN 1..10
    LOOP
        INSERT INTO MEMBER VALUES(SEQ_MEM_MEMBER_NO.NEXTVAL, '개인', 'member'|| SEQ_MEM_MEMBER_NO.CURRVAL, '1111', 'member02@collaverse.co.kr', '01022222222', '개인회원'|| SEQ_MEM_MEMBER_NO.CURRVAL, 'profile_basic.png', NULL, NULL, DEFAULT, DEFAULT, DEFAULT, '40', 'woman');
    END LOOP;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/

COMMIT;

-- 3/20 여 30대 5명
BEGIN
    FOR N IN 1..5
    LOOP
        INSERT INTO MEMBER VALUES(SEQ_MEM_MEMBER_NO.NEXTVAL, '개인', 'member'|| SEQ_MEM_MEMBER_NO.CURRVAL, '1111', 'member02@collaverse.co.kr', '01022222222', '개인회원'|| SEQ_MEM_MEMBER_NO.CURRVAL, 'profile_basic.png', NULL, NULL, DEFAULT, DEFAULT, DEFAULT, '30', 'woman');
    END LOOP;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/

COMMIT;


INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 35, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 35, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 36, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 36, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 37, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 37, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 38, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 38, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 39, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 39, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 40, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 40, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 41, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 41, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 42, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 42, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 43, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 43, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 44, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 44, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 45, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 45, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 46, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 46, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 47, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 47, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 48, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 48, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 49, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 49, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 50, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 50, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 51, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 51, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 52, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 52, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 53, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 53, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 54, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 54, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 55, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 55, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 56, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 56, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 57, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 57, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 58, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 58, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 59, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 59, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 60, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 60, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 61, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 61, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 62, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 62, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 63, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 63, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 64, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 64, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 65, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 65, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 66, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 66, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 67, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 67, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 68, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 68, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 69, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 69, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 70, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 70, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 71, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 71, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 72, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 72, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 73, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 73, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 74, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 74, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 75, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 75, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 76, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 76, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 77, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 77, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 78, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 78, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 79, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 79, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 80, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 80, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 81, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 81, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 82, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 82, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 83, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 83, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 84, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 84, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 85, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 85, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 86, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 86, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 87, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 87, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 88, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 88, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 89, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 89, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 90, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 90, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 91, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 91, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 92, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 92, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 93, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 93, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 94, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 94, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 95, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 95, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 96, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 96, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 97, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 97, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 98, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 98, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 99, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 99, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 100, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 100, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 101, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 101, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 102, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 102, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 103, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 103, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 104, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 104, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 105, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 105, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 106, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 106, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 107, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 107, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 108, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 108, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 109, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 109, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 110, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 110, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 111, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 111, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 112, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 112, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 113, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 113, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 114, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 114, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 115, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 115, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 116, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 116, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 117, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 117, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 118, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 118, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 119, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 119, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 120, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 120, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 121, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 121, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 122, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 122, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 123, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 123, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 124, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 124, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 125, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 125, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 126, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 126, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 127, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 127, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 128, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 128, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 129, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 129, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 130, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 130, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 131, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 131, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 132, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 132, DEFAULT, 1);

INSERT INTO FOLLOWING(FOLLOWING_NO, FROM_MEM_NO, TO_MEM_NO, FOLLOWING_CREATE_DATE, FOLLOWINGCHECK)
VALUES(SEQ_FOLLOWING_NO.NEXTVAL, 133, 5, DEFAULT, 1);

INSERT INTO FOLLOWER(FOLLOWER_NO, TO_MEM_NO, FROM_MEM_NO, FOLLOWER_CREATE_DATE, FOLLOWERCHECK)
VALUES(SEQ_FOLLOWER_NO.NEXTVAL, 5, 133, DEFAULT, 1);

COMMIT;
