-- 03/07 MON 업데이트 : PROMOTION 테이블에 HEART_HIT 추가
ALTER TABLE PROMOTION ADD HEART_HIT;
COMMENT ON COLUMN PROMOTION.HEART_HIT IS '좋아요수';

-- 03/07 MON 업데이트 : HEART 테이블 작성 

CREATE TABLE HEART (
HEART_NO NUMBER CONSTRAINT H_HEAR_NO_PK PRIMARY KEY,
HEART_PMT_NO NUMBER CONSTRAINT H_PMT_NO_NN NOT NULL,
HEART_MEM_NO NUMBER CONSTRAINT H_HEART_MEM_NO_NN NOT NULL,
HEARTCHECK NUMBER DEFAULT 0 CONSTRAINT H_MEMBER_NO_CH CHECK (HEARTCHECK IN(0, 1)),

FOREIGN KEY (HEART_PMT_NO) REFERENCES PROMOTION(PMT_NO) ON DELETE CASCADE,
FOREIGN KEY (HEART_MEM_NO) REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE
);

COMMENT ON COLUMN HEART.HEART_NO IS '좋아요번호';
COMMENT ON COLUMN HEART.HEART_PMT_NO IS '좋아요_한_프로모션번호';
COMMENT ON COLUMN HEART.HEART_MEM_NO IS '좋아요_한_회원번호';
COMMENT ON COLUMN HEART.HEARTCHECK IS '중복체크_방지용';

CREATE SEQUENCE SEQ_H_HEART_NO;

COMMIT;

-- 테스트용
---- sdaaeng 21 은 체크 안한거 
--INSERT INTO HEART VALUES(SEQ_H_HEART_NO.NEXTVAL, 1, 21, 0);
---- dudu 41 은 체크 한거 
--INSERT INTO HEART VALUES(SEQ_H_HEART_NO.NEXTVAL, 1, 41, 1);

-- hearCheck 가 0 인지 1인지 확인해주는 쿼리문
SELECT  HEART_PMT_NO,HEART_MEM_NO, HEARTCHECK 
FROM HEART
WHERE HEART_PMT_NO = 1
    AND HEART_MEM_NO=21;

-- 01. 게시글 추천수 올리는 쿼리문
--updateHeart
--UPDATE PROMOTION
--SET HEARTHIT = HEARTHIT + 1
--WHERE HEART_PMT_NO = #{ HEART_PMT_NO }

-- 02. 게시글 추천수 취소 쿼리문
--updateHeartCancel
--UPDATE PROMOTION
--SET HEARTHIT = HEARTHIT - 1
--WHERE HEART_PMT_NO = #{ HEART_PMT_NO }

-- 03. 하트 클릭 시 HEART 테이블에 만드는 쿼리문
-- 시퀀스 생성 대신에 저렇게 처리함
-- insertHeart
--INSERT INTO HEART(HEART_NO, HEART_PMT_NO, HEART_MEM_NO)
--VALUES ((SELECT NVL(MAX(HEART_NO), 0) + 1 FROM HEART), #{ HEART_PMT_NO }, #{ HEART_MEM_NO })

-- 04. 하트 취소 시 HEART 테이블에서 빼는 쿼리문
-- deleteHeart
--DELETE FROM HEART 
--WHERE HEART_PMT_NO = #{ HEART_PMT_NO }
--    AND HEART_MEM_NO = #{ HEART_MEM_NO } 

-- 05. 하트 클릭 시 CHECK 를 1로 만들어 중복 방지
-- updateHeartCheck
--UPDATE HEART
--SET HEARTCHECK = 1
--WHERE HEART_PMT_NO = #{ HEART_PMT_NO }
--    AND HEART_MEM_NO = #{ HEART_MEM_NO }


-- 06. 하트 취소 시 CHECK 를 다시 0 으로 만듦
-- updateHeartCheckCancel
--UPDATE HEART
--SET HEARTCHECK = 0
--WHERE HEART_PMT_NO = #{ HEART_PMT_NO }
--    AND HEART_MEM_NO = #{ HEART_MEM_NO }

-- 07. 0506 을 뺴고 컨트롤러에서 제어하는 하트 중복방지문
-- heartCheck
--SELECT COUNT(*)
--FROM HEART
--WHERE HEART_PMT_NO = #{ HEART_PMT_NO }
--    AND HEART_MEM_NO = #{ HEART_MEM_NO } 


















