
-- COLLAVERSE 계정 생성
-- CREATE USER COLLAVERSE IDENTIFIED BY COLLAVERSE;
-- GRANT RESOURCE, CONNECT TO COLLAVERSE;

------------------------------------------------
---------------- 카테고리 테이블 -----------------
------------------------------------------------

CREATE TABLE CATEGORY (
    NO NUMBER(20) PRIMARY KEY,
    C_NAME VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN CATEGORY.NO IS '카테고리번호';
COMMENT ON COLUMN CATEGORY.C_NAME IS '카테고리명';

CREATE SEQUENCE SEQ_CATEGORY_NO;

INSERT INTO CATEGORY VALUES(SEQ_CATEGORY_NO.NEXTVAL, '리빙');
INSERT INTO CATEGORY VALUES(SEQ_CATEGORY_NO.NEXTVAL, '문화');
INSERT INTO CATEGORY VALUES(SEQ_CATEGORY_NO.NEXTVAL, '식품');
INSERT INTO CATEGORY VALUES(SEQ_CATEGORY_NO.NEXTVAL, '테크');
INSERT INTO CATEGORY VALUES(SEQ_CATEGORY_NO.NEXTVAL, '패션');

-- DROP TABLE CATEGORY;
-- DROP SEQUENCE SEQ_CATEGORY_NO;

------------------------------------------------
---------------- 프로모션 테이블 -----------------
------------------------------------------------

CREATE TABLE PROMOTION (	
    PMT_NO NUMBER(10) PRIMARY KEY,
    PMT_TITLE VARCHAR2(100),
    PMT_IMG_PATH VARCHAR2(100),
    PMT_CONTENT VARCHAR2(2000),
    PMT_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(PMT_STATUS IN('Y', 'N')),
    START_DATE DATE,
    END_DATE DATE,
    READCOUNT NUMBER,
    C_NO NUMBER(20),
    FOREIGN KEY (C_NO) REFERENCES CATEGORY (NO) 
);

COMMENT ON COLUMN PROMOTION.PMT_NO IS '프로모션 번호';
COMMENT ON COLUMN PROMOTION.PMT_TITLE IS '프로모션 제목';
COMMENT ON COLUMN PROMOTION.PMT_IMG_PATH IS '이미지 경로';
COMMENT ON COLUMN PROMOTION.PMT_CONTENT IS '프로모션 설명';
COMMENT ON COLUMN PROMOTION.PMT_STATUS IS '프로모션 상태';
COMMENT ON COLUMN PROMOTION.START_DATE IS '시작일';
COMMENT ON COLUMN PROMOTION.END_DATE IS '종료일';
COMMENT ON COLUMN PROMOTION.READCOUNT IS '조회수';
COMMENT ON COLUMN PROMOTION.C_NO IS '카테고리번호';

CREATE SEQUENCE SEQ_PROMOTION_NO;

-- 프로모션 데이터 추가 --

------------------------------------------------
----------------- 제품 테이블 -------------------
------------------------------------------------

CREATE TABLE PRODUCT (	
    PRO_NO NUMBER(10) PRIMARY KEY,
    PRO_NAME VARCHAR2(100),
    PRO_PRICE VARCHAR2(100),
    PRO_CONTENT VARCHAR2(2000),
    PRO_QTY VARCHAR2(20), 
    PRO_IMG_PATH VARCHAR2(100),
    
    C_NO NUMBER(20),
    PMT_NO NUMBER(10),
    FOREIGN KEY (C_NO) REFERENCES CATEGORY (NO),
    FOREIGN KEY (PMT_NO) REFERENCES PROMOTION (PMT_NO) 
);

COMMENT ON COLUMN PRODUCT.PRO_NO IS '제품 번호';
COMMENT ON COLUMN PRODUCT.PRO_NAME IS '제품명';
COMMENT ON COLUMN PRODUCT.PRO_PRICE IS '가격';
COMMENT ON COLUMN PRODUCT.PRO_CONTENT IS '제품 설명';
COMMENT ON COLUMN PRODUCT.PRO_QTY IS '구매가능 수량';
COMMENT ON COLUMN PRODUCT.SP_IMG_PATH IS '이미지 경로';
COMMENT ON COLUMN PRODUCT.C_NO IS '카테고리번호';
COMMENT ON COLUMN PRODUCT.PMT_NO IS '프로모션 번호';

CREATE SEQUENCE SEQ_PRODUCT_NO;

-- DROP TABLE PRODUCT;
-- DROP SEQUENCE SEQ_PRODUCT_NO;

-- 제품 데이터 추가 --

------------------------------------------------
----------------- 브랜드 테이블 -------------------
------------------------------------------------

CREATE TABLE BRAND (
    BR_NAME VARCHAR2(50),
    BR_GROUP VARCHAR2 (20),
    MEMBER_NO NUMBER(10)
);

-- 회원번호 외래키 설정하기 

COMMENT ON COLUMN BRAND.BR_NAME IS '카테고리번호';
COMMENT ON COLUMN BRAND.BR_GROUP IS '카테고리명';
COMMENT ON COLUMN BRAND.MEMBER_NO IS '회원번호';

-- 브랜드 데이터 추가 --

