-- 되는거
SELECT ROWNUM, RESULT.*
FROM (SELECT ROWNUM, RANDOM.* 
        FROM (MEMBER SAMPLE(30)) RANDOM
        ORDER BY MEMBER_NO) RESULT
WHERE ROWNUM <=5
    AND MEMBER_ROLE IN ('개인', '기업');
--

-- 실험중
SELECT RESULT.*
FROM (SELECT ROWNUM, RANDOM.* 
        FROM (SELECT *
              FROM MEMBER SAMPLE(30)) RANDOM
        ORDER BY MEMBER_NO) RESULT
WHERE ROWNUM =5
    AND MEMBER_ROLE IN ('개인', '기업');
--

-- 블로그 보고 따라해서 범위는 맞춤 --
SELECT *
FROM (SELECT ROWNUM NUMROW, AA.*
    FROM (SELECT * FROM MEMBER
    ORDER BY MEMBER_NO)AA)
WHERE NUROWM >1 AND NUMROW <=10;
-- https://mainia.tistory.com/267

-- OKKY 와 이거된다 이걸로 간다 -- https://okky.kr/article/60167
SELECT A.* 
FROM (SELECT ROWNUM NUMROW, MEMBER.*
    FROM MEMBER) A
WHERE A.NUMROW IN (2, 4, 6)
    AND MEMBER_ROLE IN ('개인', '기업');
    
-- 되는거
SELECT ROWNUM, RESULT.*
FROM (SELECT ROWNUM, RANDOM.* 
        FROM (MEMBER SAMPLE(30)) RANDOM
        ORDER BY MEMBER_NO) RESULT
WHERE ROWNUM <=5
    AND MEMBER_ROLE IN ('개인', '기업');
--

-- ★★★★★★ 최종 : BETWEEN, IN 도 되는 버전)
SELECT RESULT.* 
FROM (SELECT ROWNUM NUMROW, RANDOM.* 
        FROM (MEMBER SAMPLE(30)) RANDOM
        ORDER BY MEMBER_NO) RESULT
WHERE RESULT.NUMROW BETWEEN 3 AND 12
    AND MEMBER_ROLE IN ('개인', '기업');
    
SELECT RESULT.* 
FROM (SELECT ROWNUM NUMROW, MEMBER.* 
        FROM MEMBER
        ORDER BY MEMBER_NO) RESULT
WHERE RESULT.NUMROW IN (2, 5, 6)
    AND MEMBER_ROLE IN ('개인', '기업');
    
-- 인피니트 스크롤 도전
-- 아래 구문에서 ㅠSELECT RESULT.* 
SELECT RESULT.* 
FROM (SELECT ROWNUM NUMROW,ID, NICKNAME, PROFILE_IMG, MEMBER_ROLE
		FROM MEMBER
        ORDER BY MEMBER_NO) RESULT
WHERE RESULT.NUMROW BETWEEN (14 * 1 + 1) AND (14 * (1 + 1))
    AND MEMBER_ROLE IN ('개인', '기업');
    
SELECT ID, NICKNAME, PROFILE_IMG
		FROM MEMBER
		WHERE MEMBER_ROLE IN ('개인', '기업')